### ISSUE TITLE
Triangles

### ISSUE THREAD

**Issue by ghost** [Track-Gen/TrackGen#18]
I like this idea for a simple track generator a lot. However, there are some improvements that could be made. One of which could be the triangles being a bit more like the WPTC's. If you would like me to clarify some more I can do that as well. Thank you for reading this.

**Comment by ShuchirJ** [comment]
Hey there! Thanks for showing an interest in TrackGen. I cannot help you with the current issue, but another member will get back to you shortly. Meanwhile, I have also transferred the issue to our official repo, as the other repo is only for issues/comments/concerns with specifically the desktop app.

**Comment by ghost** [comment]
Ah okay, sorry about that then. I just wanted to see if the triangle could be improved on. Thank you though.

**Comment by ghost** [comment]
I also tried seeing if I could run this locally myself to see if I could make the triangle be a bit better shaped. However, the images won't load on them when I do a local http server.

**Comment by Coding-Cactus** [comment]
Hi @Reno-Rex we are trying to get the shapes as close to WPTC's as we can, so would you mind giving a side-by-side of the two so I can see what needs to be done. Thanks!

**Comment by ghost** [comment]
Sure thing, I've gotten a pretty good estimate on what they both look like at the moment. Here you go.

![triangle comparisons](https://user-images.githubusercontent.com/19253701/133081843-f45da0cd-a127-4cc2-a935-9e04bcc3e086.png)

**Comment by Coding-Cactus** [comment]
how's this 
![image](https://user-images.githubusercontent.com/65423356/133146553-cb4d2da3-dbdc-4eb6-9d5a-ac6d9f413593.png)

**Comment by ghost** [comment]
Sorry I was late, but I think that looks a lot better, thank you again.
